version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c ./entry_point.sh
    container_name: omni_service
    env_file:
      - .env
    ports:
      - ${PUBLISHED_PORT}:${TARGET_PORT}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: omni_db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer