# Generated by Django 3.2.8 on 2021-10-18 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c215169f-92f7-43d6-9533-b2455709fca4'), unique=True),
        ),
    ]
