# Generated by Django 3.2.8 on 2021-10-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0003_auto_20211017_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='products',
            new_name='product',
        ),
    ]
