# Generated by Django 3.2.8 on 2021-10-17 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0004_rename_products_stock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='amount',
            new_name='units',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('59e4ac5c-c487-4f9d-9792-79a5e6dbc79e'), unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'OUTSTANDING'), (1, 'PAID'), (2, 'DELIVERED')], default=0),
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='ecomerce.Product'),
        ),
    ]
