# Generated by Django 3.2.8 on 2021-10-18 04:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0004_auto_20211018_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('start_address', models.CharField(max_length=100)),
                ('end_address', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomerce.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
