# Generated by Django 3.2.8 on 2021-10-17 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0005_auto_20211017_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('481afef3-873c-45ff-ac01-8df4b33ac4d4'), unique=True),
        ),
    ]
