# Generated by Django 3.2.8 on 2021-10-17 22:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0006_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ad51e917-c457-4126-a19f-f009a195b6d9'), unique=True),
        ),
    ]
