# Generated by Django 3.2.8 on 2021-10-17 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0007_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('f3399401-c367-4a53-b6bd-b06e6f3dace5'), unique=True),
        ),
    ]
