# Generated by Django 3.2.8 on 2021-10-17 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0008_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2d1fa033-c2d1-49ef-ab77-54885217eb10'), unique=True),
        ),
    ]
