# Generated by Django 3.2.8 on 2021-10-17 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0009_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('01d9d5c8-8de2-460a-b3b1-4f06e247b229'), unique=True),
        ),
    ]
