# Generated by Django 3.2.8 on 2021-10-17 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0010_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('bcdfee35-d15a-402c-8c43-b3d6d5d9d873'), unique=True),
        ),
    ]
