# Generated by Django 3.2.8 on 2021-10-17 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0011_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.UUID('95edf3e6-7e00-486f-a977-ee32d00f6ac4'), unique=True),
        ),
    ]
